openapi: 3.0.1
info:
  title: IPA - Indice Domicili Digitali delle PA e GPS
  
  description: |-
    API rese disponibili da IPA per la consultazione degli aggiornamenti delle AOO

    Pattern Model applicati:
    - [ID_AUTH_CHANNEL_01] Direct Trust Transport-Level Security
    - [BLOCK_REST] Blocking REST    

  contact:
    name: AgID - Agenzia per l'Italia Digitale
    url: https://www.agid.gov.it/
  
  license:
    name: CC BY-NC-SA 4.0
    url: https://creativecommons.org/licenses/by-nc-sa/4.0/
  
  version: 1.0.0

servers:
  - url: <TOBEDEFINE>
    description: Server URL

paths:
  /AOOs:
    get:
      description: consultazione degli aggironamenti delle AOO

      operationId: getAOOs
            
      responses:
        '200':
          description: JSON della AOO
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AOOs'
          
        '400':
          $ref: '#/components/responses/400'
        '401':
          $ref: '#/components/responses/401'
        '403':
          $ref: '#/components/responses/403'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
        '503':
          $ref: '#/components/responses/503'
  
components:

  responses:
    '400':
      description: BAD_REQUEST
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '401':
      description: UNAUTHORIZED
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '403':
      description: FORBIDDEN
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '404':
      description: NOT_FOUND
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '500':
      description: INTERNAL_SERVER_ERROR
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'
    '503':
      description: SERVICE_UNAVAILABLE
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    CodiceFiscaleEnte:
      description: Codice Fiscale dell'ENTE      
      type: string
      pattern: ^([0-9]{11})$
      example: 12345678901

    CodiceUniAOO:
      description: Codice unico dell'AOO
      type: string
      maxLength: 7

    AOOs:
      description: elenco dei JSON degli ENTI
      type: array
      items:
        $ref: '#/components/schemas/AOO'


    AOO:
      description: AOO di un ENTE
      type: object
      required:
        - codice_fiscale_ente
        - codice_ipa_ente
        - codice_uni_aoo
        - descrizione_aoo
        - data_istituzione
        - data_aggiornamento
        - operation
        
      properties:
        codice_fiscale_ente:
          description: codice fiscale dell'ENTE
          $ref: '#/components/schemas/CodiceFiscaleEnte'
        codice_ipa_ente:
          description: codice IPA dell'ENTE
          $ref: '#/components/schemas/CodiceIPA'
        codice_uni_aoo:
          $ref: '#/components/schemas/CodiceUniAOO'
        codice_aoo:
          type: string
          maxLength: 100
        descrizione_aoo:
          type: string
          maxLength: 1000
        protocollo_informatico:
          type: boolean
        URL_protocollo_informatico:
          type: string
          maxLength: 200
          pattern: ^((http|https)://)[-a-zA-Z0-9@:%._\\+~#?&//=]{2,256}\\.[a-z]{2,6}\\b([-a-zA-Z0-9@:%._\\+~#?&//=]*)$
        data_istituzione:
          type: string
          format: date 
        data_aggiornamento:
          type: string
          format: date
        operation:
          type: string
          maxLength: 1
          enum:
            - C
            - U
            - D

    CodiceIPA:
      description: codice ipa ENTE
      type: string
      maxLength: 100

    Error: 
      description: Modello di risposta in caso di errore     
      required:
        - status
        - type
      type: object
      properties:
        status:
          type: string
          description: Codice di errore
          example: <HTTP_CODE>
          enum:
            - '400'
            - '401'
            - '403'
            - '404'
            - '500'
            - '503'
        type:
          type: string
          description: Tipologia di errore
          example: <HTTP_STATUS>
          enum:
            - BAD_REQUEST
            - UNAUTHORIZED
            - FORBIDDEN
            - NOT_FOUND
            - INTERNAL_SERVER_ERROR
            - SERVICE_UNAVAILABLE
        detail:
          type: string
          description: Descrizione di dettaglio dello specifico problema verificatosi
          example: <detail_error>
      
    
  securitySchemes:
    bearerAuth:
      scheme: bearer
      bearerFormat: JWT
      type: http
      description: |-
        Implementazione conforme ad RFC8725.

security:
  - bearerAuth: []